### PR TITLE
Elisp syntax

### PR DESCRIPTION
**Pull request by wasamasa**
Addresses #1 and #2.

### CODE REVIEW

**Comment by pchaigno** [comment]
@infininight Did you get a chance to look into this?

**Comment by infininight** [comment]
@wasamasa In 631bf61d0c28db826b5fbab479baf298436c549d I presume you meant to replace the current rule rather than duplicate it?

**Comment by wasamasa** [comment]
@infininight Oh right, I did only test with the online tool for grammars.

**Comment by infininight** [comment]
I've pulled these changes in. Simplified the second commit slightly as we didn't need a complete word boundary replacement as we were already have a narrow match for the interior so we only needed to check the outside boundaries. Thanks!

Note that these changes will be available in TextMate immediately, for Github they will be updated next time they deploy linguist which is typically every few weeks.

**Comment by pchaigno** [comment]
Thanks @infininight!

**Pull request closed without merging**
